using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Lagrange.Milky.Generator.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Lagrange.Milky.Generator.Api;

[Generator(LanguageNames.CSharp)]
public class ApiExtensionGenerator : IIncrementalGenerator
{
    private const string ApiHandlerAttributeTypeName = "Lagrange.Milky.Api.Attributes.ApiHandlerAttribute";
    private const string IApiHandlerTypeName = "Lagrange.Milky.Api.Handlers.IApiHandler`2";
    private const string INoRequestApiHandlerTypeName = "Lagrange.Milky.Api.Handlers.INoRequestApiHandler`1";
    private const string INoResultApiHandlerTypeName = "Lagrange.Milky.Api.Handlers.INoResultApiHandler`1";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerInfos = context.SyntaxProvider.ForAttributeWithMetadataName(
            ApiHandlerAttributeTypeName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: GetHandleInfo
        ).Collect();

        context.RegisterSourceOutput(
            handlerInfos,
            static (context, handlerInfos) =>
            {
                var validHandlerInfos = FilterHandlerInfoAndReportDiagnostics(context, handlerInfos);

                string generatedCode = GenerateSourceCode(validHandlerInfos);
                context.AddSource("Lagrange.Milky.Api.Extensions.EventExtension.g.cs", generatedCode);
            }
        );
    }

    private (string, string, int, bool, Location?) GetHandleInfo(GeneratorAttributeSyntaxContext context, CancellationToken token)
    {
        var compilation = context.SemanticModel.Compilation;
        var handlerSymbol = (INamedTypeSymbol)context.TargetSymbol;

        string handlerTypeName = handlerSymbol.ToDisplayString();

        var attributeData = context.Attributes.First();
        string name = (string)attributeData.ConstructorArguments
            .First()
            .Value!;
        int lifetime = (int?)attributeData
            .NamedArguments
            .FirstOrDefault(a => a.Key == "Lifetime")
            .Value
            .Value
            ?? 0;

        var handlerInterfaceSymbol = compilation.GetTypeByMetadataName(IApiHandlerTypeName);
        var noRequestHandlerInterfaceSymbol = compilation.GetTypeByMetadataName(INoRequestApiHandlerTypeName);
        var noResultHandlerInterfaceSymbol = compilation.GetTypeByMetadataName(INoResultApiHandlerTypeName);
        bool isImpl = handlerSymbol.AllInterfaces
            .Any(s => s.OriginalDefinition.DefaultEquals(handlerInterfaceSymbol)
                || s.OriginalDefinition.DefaultEquals(noRequestHandlerInterfaceSymbol)
                || s.OriginalDefinition.DefaultEquals(noResultHandlerInterfaceSymbol));

        var location = handlerSymbol.Locations.FirstOrDefault();

        return (handlerTypeName, name, lifetime, isImpl, location);
    }

    private static IEnumerable<(string, string, int)> FilterHandlerInfoAndReportDiagnostics(SourceProductionContext context, ImmutableArray<(string, string, int, bool, Location?)> handlerInfos)
    {
        var apiNames = new HashSet<string>(StringComparer.Ordinal);
        var result = new List<(string, string, int)>();

        foreach ((string handlerTypeName, string apiName, int lifetime, bool isImpl, var location) in handlerInfos)
        {
            if (!isImpl)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ApiDiagnosticDescriptors.MustImplementInterfaceError,
                    location,
                    handlerTypeName
                ));
                continue;
            }

            if (!apiNames.Add(apiName))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ApiDiagnosticDescriptors.DuplicateApiNameError,
                    location,
                    handlerTypeName,
                    apiName
                ));
                continue;
            }

            result.Add((handlerTypeName, apiName, lifetime));
        }

        return result;
    }

    private static string GenerateSourceCode(IEnumerable<(string, string, int)> handlerInfos)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine();
        builder.AppendLine("namespace Lagrange.Milky.Api.Extensions;");
        builder.AppendLine();
        builder.AppendLine("public static partial class ApiExtension");
        builder.AppendLine("{");
        builder.AppendLine("    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddApiHandlers(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        builder.AppendLine("    {");
        foreach (var (handlerName, eventName, lifetime) in handlerInfos)
        {
            builder.AppendLine($"        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Api.Handlers.IApiHandler), typeof({handlerName}), (Microsoft.Extensions.DependencyInjection.ServiceLifetime){lifetime}));");
        }
        builder.AppendLine("        return services;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }
}