name: Build Lagrange.Milky

on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/milky-build.yaml
      - Lagrange.Codec/**
      - Lagrange.Core/**
      - Lagrange.Milky/**
      - Lagrange.Milky.Implementation.Api.Generator/**
      - Lagrange.Proto/**
      - Lagrange.Proto.Generator/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/milky-build.yaml
      - Lagrange.Codec/**
      - Lagrange.Core/**
      - Lagrange.Milky/**
      - Lagrange.Milky.Implementation.Api.Generator/**
      - Lagrange.Proto/**
      - Lagrange.Proto.Generator/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            binary-extension: '.exe'
          - os: macos-latest
            rid: osx-arm64
            binary-extension: ''
          - os: ubuntu-latest
            rid: linux-x64
            binary-extension: ''

    env:
      RUNTIME_IDENTIFIER: ${{ matrix.rid }}

    steps:
      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y clang zlib1g-dev

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish
        run: dotnet publish Lagrange.Milky -c Release -r ${{ matrix.rid }}

      - if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Lagrange.Milky-${{ matrix.rid }}
          path: Lagrange.Milky/bin/Release/net10.0/${{ matrix.rid }}/publish/Lagrange.Milky${{ matrix.binary-extension }}
      - if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Lagrange.Milky-${{ matrix.rid }}-symbol-files
          path: |
            Lagrange.Milky/bin/Release/net10.0/${{ matrix.rid }}/publish/*
            !Lagrange.Milky/bin/Release/net10.0/${{ matrix.rid }}/publish/Lagrange.Milky${{ matrix.binary-extension }}
