name: Nuget push Lagrange.Proto

on:
  push:
    branches:
      - main
      - master
    paths:
      - "Lagrange.Proto/Lagrange.Proto.csproj"
  workflow_dispatch:

jobs:
  nuget-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - id: nuget-login
        uses: NuGet/login@v1
        with:
          user: Linwenxuan04

      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10'
      
      - run: dotnet pack -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg Lagrange.Proto

      - run: dotnet nuget push ./Lagrange.Proto/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }}